# Generated by Django 3.1.5 on 2021-01-22 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(null=True, to='api.Actors'),
        ),
    ]
