# Generated by Django 3.1.5 on 2021-01-22 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_movie_actors'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='category',
            field=models.ManyToManyField(null=True, to='api.Category'),
        ),
    ]
