# Generated by Django 3.1.5 on 2021-01-23 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_movie_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='actors',
        ),
        migrations.AddField(
            model_name='actors',
            name='movie',
            field=models.ManyToManyField(to='api.Movie'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.ManyToManyField(to='api.Category'),
        ),
    ]
