# Generated by Django 3.1.5 on 2021-01-23 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210123_0105'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.movie'),
        ),
    ]
