# Generated by Django 3.1.5 on 2021-01-23 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_director_movie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='director',
            old_name='name',
            new_name='lastName',
        ),
        migrations.AddField(
            model_name='director',
            name='firstName',
            field=models.CharField(default='', max_length=45),
        ),
    ]
