# Generated by Django 3.1.5 on 2021-01-23 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210123_0129'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='seats',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.seats'),
        ),
        migrations.AddField(
            model_name='movietime',
            name='movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.movie'),
        ),
    ]
