# Generated by Django 3.1.5 on 2021-01-23 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210123_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='movieTime',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.movietime'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seats',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.seats'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.ManyToManyField(related_name='category', to='api.Category'),
        ),
    ]
