# Generated by Django 3.1.5 on 2021-01-23 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210123_1126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='director',
            name='movie',
        ),
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.director'),
        ),
        migrations.AlterField(
            model_name='actors',
            name='movie',
            field=models.ManyToManyField(related_name='movie', to='api.Movie'),
        ),
    ]
