# Generated by Django 3.1.5 on 2021-01-23 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210123_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=45)),
                ('phone_number', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Seans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='hall',
            name='seats',
        ),
        migrations.RemoveField(
            model_name='movietime',
            name='movie',
        ),
        migrations.RenameField(
            model_name='director',
            old_name='dateOfBirth',
            new_name='birthday',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='dateOfReservation',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='director',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='movieTime',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='seats',
        ),
        migrations.AddField(
            model_name='reservation',
            name='ticket',
            field=models.CharField(choices=[('reduced', 'reduced'), ('normal', 'normal')], default='normal', max_length=15),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movie', to='api.director'),
        ),
        migrations.DeleteModel(
            name='Actors',
        ),
        migrations.DeleteModel(
            name='Hall',
        ),
        migrations.DeleteModel(
            name='MovieTime',
        ),
        migrations.DeleteModel(
            name='Seats',
        ),
        migrations.AddField(
            model_name='seans',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seans', to='api.movie'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to='api.client'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seans',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to='api.seans'),
        ),
    ]
