# Generated by Django 3.1.5 on 2021-01-23 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210123_1530'),
    ]

    operations = [
        migrations.RenameField(
            model_name='director',
            old_name='firstName',
            new_name='first_Name',
        ),
        migrations.RenameField(
            model_name='director',
            old_name='lastName',
            new_name='last_Name',
        ),
    ]
