# Generated by Django 3.1.5 on 2021-01-23 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20210123_1549'),
    ]

    operations = [
        migrations.RenameField(
            model_name='director',
            old_name='first_Name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='director',
            old_name='last_Name',
            new_name='last_name',
        ),
    ]
