# Generated by Django 3.1.5 on 2021-01-23 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20210123_1549'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ('last_name',)},
        ),
        migrations.AlterModelOptions(
            name='director',
            options={'ordering': ('last_name',)},
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ('title',)},
        ),
        migrations.AlterModelOptions(
            name='seans',
            options={'ordering': ('date',)},
        ),
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.CharField(max_length=255),
        ),
    ]
