# Generated by Django 3.1.5 on 2021-01-24 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20210123_2222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='runningTime',
            new_name='running_time',
        ),
        migrations.AddField(
            model_name='movie',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
