# Generated by Django 3.1.5 on 2021-01-24 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20210124_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seans',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seans',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
