# Generated by Django 3.1.5 on 2021-01-24 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20210124_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
