# Generated by Django 3.1.5 on 2021-01-25 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20210125_0010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='director',
            name='birthday',
        ),
        migrations.AddField(
            model_name='director',
            name='stars',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='director',
            name='year_of_birtday',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
