# Generated by Django 3.1.5 on 2021-01-25 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20210125_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='year_of_birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
