# Generated by Django 3.1.5 on 2021-01-25 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20210125_0157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='director',
            old_name='year_of_birthday',
            new_name='birthday',
        ),
    ]
